services:
  app:
    container_name: nestjs-app
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c " npx prisma generate 
      && npx prisma migrate deploy 
      && npm run build 
      && npm run start 
      "

  db:
    container_name: postgres-db
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worder
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
